nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/vspedr

projects_url: http://github.com/vspedr

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/vspedr
        twitter: http://twitter.com/vspedr
        facebook: http://facebook.com/vspedrazzi
        linkedin: https://www.linkedin.com/in/victor-pedrazzi-41062b6a/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-108534391-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
